### ISSUE TITLE
Add checkIgnore to this Repo

### ISSUE THREAD

**Issue by ajtran** [rollbar/rollbar-php-symfony3-bundle#6]
User is requesting some method similar to that of the other SDKs where we can ignore data being sent to Rollbar. This is a little trickier considering the config file is yml.

internal: https://app.intercom.io/a/apps/rlisg82q/inbox/inbox/849049/conversations/15591684072

**Comment by JoydS** [comment]
Like @ajtran is saying, it would be great if we could use checkIgnore on rollbar bundle to disable some redondant messages.

Thank you by advance !

**Comment by ArturMoczulski** [comment]
This is supported in the latest release with the following configuration in `app/config/config.yml` or `app/config/config_*.yml`:

```yaml
rollbar:
    enabled: true
    access_token: YouAccessToken
    environment: YourEnvironmentName
    check_ignore: '\MyClass::checkIgnore'
```

The `check_ignore` config option takes a PHP callable as a string.
